import Header from '../shared/widgets/header';
import './global.css';
import {Poppins,Roboto,Oregano} from "next/font/google"
import Providers from './providers';
import Footer from '../shared/widgets/footer';

export const metadata = {
  title: 'Welcome to user-ui',
  description: 'Generated by create-nx-workspace',
}

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--font-roboto"
})

const oregano = Oregano({ subsets: ["latin"], weight: ["400"], variable: "--font-oregano" })

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900"],
  variable: "--font-poppins"
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${poppins.variable} ${oregano.variable}`}>
        <Providers>
        <Header/>
        {children}
        <Footer/>
        </Providers>
        </body>
    </html>
  )
}
